services:
  web:
    build: . 
    container_name: backend_hr
    volumes:
      - static:/usr/src/app/staticfiles  
      - ./:/usr/src/app
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST} 
      IS_URL: ${IS_URL}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RESET_PASSWORD_COMMAND: ${RESET_PASSWORD_COMMAND}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - hr_redis
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations main &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py create-admin &&
             gunicorn --bind 0.0.0.0:8000 laborcount.wsgi:application"
    networks:
      - backend_network # была проблема дж не подключался к редису из за того что  они были в разных сетях имеется в виду что не в backend_network
  hr_redis:
    image: redis:7.2-alpine
    container_name: hr_redis
    ports:
      - "6399:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass Bm84qq9E8G
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Bm84qq9E8G", "ping"]  
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend_network
    
volumes:
  redis_data:
  static:

networks:
  backend_network:  # Единая сеть для всех сервисов
    driver: bridge
