version: '3.12' 
services: 
  backend: 
    build: . 
    command: python manage.py runserver 0.0.0.0:8000 
    network_mode: host 
    depends_on: 
      - db    
    volumes: 
      - ./:/usr/src/app 
    ports: 
      - 8000:8000 
  db: 
    image: postgres:15 
    container_name: db 
    volumes: 
      - postgres-data:/var/lib/postgresql/data 
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust" 
    ports: 
      - 5432:5432 
volumes: 
  postgres-data: 
    driver: local 
