

services:
  web:
    build: .  # Используем Dockerfile вместо прямого образа
    container_name: django_app
    volumes:
      - static:/usr/src/app/staticfiles  # Должно соответствовать WORKDIR в Dockerfile
      - ./:/usr/src/app
    environment:
      SECRET_KEY: "Cp4ADYDUB5G5vDtfuMhp2RtTCmtExwaP"
      DEBUG: "False"
      DATABASE_URL: "postgresql://postgres:test@5.129.207.182:5432/it"
      IS_URL: "True"
      RESET_PASSWORD_COMMAND: "use_admin_rooles_delete_this"
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      sh -c "python manage.py makemigrations main &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 laborcount.wsgi:application"

volumes:
  static: