services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: hr_eff
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mL1oGD~CQOs@BHA
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django_app
    volumes:
      - static:/app/staticfiles
      - ./:/app
    environment:
      SECRET_KEY: "Cp4ADYDUB5G5vDtfuMhp2RtTCmtExwaP"
      DEBUG: "False"
      DATABASE_URL: "postgresql://postgres:mL1oGD~CQOs@BHA@db:5432/hr_eff"
      IS_URL: "True"
      RESET_PASSWORD_COMMAND: "use_admin_rooles_delete_this"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    command: >
      sh -c "python manage.py makemigrations main &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 laborcount.wsgi:application"

volumes:
  postgres_data:
  static: