name: Deploy

on:
  push:
    branches: [master, deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker setup
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          docker --version

      - name: Pull and rebuild Docker
        run: |
          git pull origin master
          docker stop backend-pulse || true
          docker rm backend-pulse || true
          docker build -t backend-pulse .
          docker run -d -p 8000:8000 \
            --name backend-pulse \
            -e SECRET_KEY="Cm#~6$3gKv;OP5=_UC|rV'H.;T1b0b,M6Rs)snyd2%rNc*xvIA" \
            -e DEBUG="False" \
            -e IS_URL="False" \
            -e DATABASE_NAME="tracker" \
            -e DATABASE_HOST="81.200.158.11" \
            -e DATABASE_PASSWORD="UqNAZgZr%5C6.9Vk" \
            backend-pulse

      - name: Update Django environment
        env:
          SECRET_KEY: "Cm#~6$3gKv;OP5=_UC|rV'H.;T1b0b,M6Rs)snyd2%rNc*xvIA"
          DEBUG: False
          IS_URL: False
          DATABASE_NAME: tracker
          DATABASE_HOST: 81.200.158.11
          DATABASE_PASSWORD: UqNAZgZr%5C6.9Vk
        run: |
          echo "SECRET_KEY=${SECRET_KEY:?'SECRET_KEY is not set'}"
          echo "DEBUG=${DEBUG:?'DEBUG is not set'}"
          echo "IS_URL=${IS_URL:?'IS_URL is not set'}"
          echo "DATABASE_NAME=${DATABASE_NAME:?'DATABASE_NAME is not set'}"
          echo "DATABASE_HOST=${DATABASE_HOST:?'DATABASE_HOST is not set'}"
          echo "DATABASE_PASSWORD=${DATABASE_PASSWORD:?'DATABASE_PASSWORD is not set'}"