name: Deploy

on:
  push:
    branches: [master, deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # - name: Setup Docker permissions
      #   run: sudo chmod 666 /var/run/docker.sock || true

      - name: Pull latest changes
        run: git pull origin master

      - name: Create environment file
        run: |
          cat > .env << EOF
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=False
          IS_URL=False
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT || '5432' }}
          EOF
          
      - name: Stop and remove existing containers
        run: docker compose down -v --remove-orphans || true

      - name: Build and start containers
        run: docker compose up --build -d

      - name: Verify deployment
        run: |
          sleep 10
          docker ps
          docker compose logs --tail=20