name: Deploy

on:
  push:
    branches: [master, deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Pull latest changes
        run: git pull origin master

      - name: Create environment file
        run: |
          cat > .env << EOF
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          DEBUG=False
          ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS || 'localhost,127.0.0.1' }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DATABASE_PORT=${{ secrets.DATABASE_PORT || '5432' }}
          REDIS_URL=redis://redis:6379/0
          EOF

      - name: Stop and remove existing containers
        run: sudo -u runner docker compose down -v --remove-orphans || true

      - name: Build and start containers
        run: sudo -u runner docker compose up --build -d

      - name: Run database migrations
        run: sudo -u runner docker compose exec web python manage.py migrate --noinput || true

      - name: Collect static files
        run: sudo -u runner docker compose exec web python manage.py collectstatic --noinput --clear || true

      - name: Verify deployment
        run: |
          sleep 15
          sudo -u runner docker ps -a
          sudo -u runner docker compose logs --tail=50 web
          
