name: Deploy

on:
  push:
    branches: [master, deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker setup
        run: |
          sudo chmod 666 /var/run/docker.sock || true
          docker --version

      - name: Pull and rebuild Docker
        run: |
          git pull origin master
          docker stop backend-pulse || true
          docker rm backend-pulse || true
          docker build -t backend-pulse .
          docker run -d -p 8000:8000 --name backend-pulse backend-pulse

      - name: Update Django environment
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: False
          IS_URL: False
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          echo "${{ secrets.SECRET_KEY }} APP SHOULD WORK "
          echo "DEBUG=${DEBUG:?'DEBUG is not set'}"
          echo "IS_URL=${IS_URL:?'IS_URL is not set'}"
      